bot.name=Casinych
bot.token=8464618541:AAEKBiFSMm0h8qFBWJRHmcUjkl4rWRraIgs

spring.datasource.url=jdbc:postgresql://localhost:65432/bot-db
spring.datasource.username=postgres
spring.datasource.password=bot7654321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
